### PR TITLE
Process fault messages

### PR DESCRIPTION
**Pull request by fsaris**

### CODE REVIEW

**Comment by wimb0** [comment]
The error handling looks great. Seems to work fine too.

**Comment by wimb0** [comment]
About the refactor Hub: I kept that separated to make it possible to change the readout for the inverter static data to a longer interval. Once per hour or so. As it is data that never changes.

**Review by wimb0 — APPROVED** [review]

**Comment by fsaris** [comment]
> About the refactor Hub: I kept that separated to make it possible to change the readout for the inverter static data to a longer interval. Once per hour or so. As it is data that never changes.

It's still separated only tried to prevent some unnecessary indents.

**Comment by fsaris** [comment]
> The error handling looks great. Seems to work fine too.

Waiting for an error to a cure to fully test is. That's also why I added the debug message.

Once I processed a real error msg I will remove the draft flag from the PR.

Did you already have a error message?

**Comment by wimb0** [comment]
> 
> 
> > The error handling looks great. Seems to work fine too.
> 
> Waiting for an error to a cure to fully test is. That's also why I added the debug message.
> 
> Once I processed a real error msg I will remove the draft flag from the PR.
> 
> Did you already have a error message?

Yes, I forced an error and tested with a separate script.
(https://github.com/wimb0/saj_modbus/blob/main/read_invertor_errors.py)
Did not check it with the actual integration in HA.
Forcing an error is easy, just turn off the Current Breaker.

What I got is:
```
faultMsg 0x00000000 0x00800000 0x00800000
Fault message: Code 24: Master Phase1 No Grid Error, Code 73: Slave Phase1 No Grid Error
```

**Comment by fsaris** [comment]
All looks good, ready to go.

Tnx for the test hint ;)

**Comment by wimb0** [comment]
Thanks for the work on this. It's available in release 1.4.0.
I was struggling with this for a while. Didn't know you could do hex lookup/conversion this easy in Python.

**Comment by fsaris** [comment]
> Thanks for the work on this. It's available in release 1.4.0.

Your welcome :) 

> I was struggling with this for a while. Didn't know you could do hex lookup/conversion this easy in Python.

Had some experience with hex and binary comparison due to my work on a Bluetooth HA integration ...

But in the end HEX values are just integers in python. The `0x...` is mostly a visual representation. I kept the values in the `const.py` in HEX as that makes it easier to check them against the modbus documentation

**Pull request merged**
