### PR TITLE
Report power factor as persentage

### PR DESCRIPTION
**Pull request by fsaris**
HA expects power factor in %.
When in % the history is shown as a graph

Followup of #50

### CODE REVIEW

**Comment by wimb0** [comment]
That is weird. Power factor is something in a range from -1.0 to 1.0.
The unit for that is φ (cos-phi), it is not a percentage of something.

**Comment by fsaris** [comment]
Okay, I see that measurement to for other components. Will dive into this next days/week.

The % value was based on https://www.home-assistant.io/integrations/sensor/#device-class

**Comment by fsaris** [comment]
Your correct the `%` was added to get tests green and because HA needs a unit to recognize the value as a numeric value. But value should be as is.

Think will add the ` ` (space) as temp workaround to get the graphs in HA.


For reference:
- Initial architecture discussion https://github.com/home-assistant/architecture/issues/397
- Initial change that added power_factor https://github.com/home-assistant/core/pull/36800
- test still mentions the value should be between -1 and 1 https://github.com/home-assistant/core/blob/de0460de6170b360fe6746e5f2963a04e6063547/tests/testing_config/custom_components/test/sensor.py#L41
- Follow up discussion https://github.com/home-assistant/architecture/issues/469

**Comment by fsaris** [comment]
Some more insides on this https://github.com/home-assistant/architecture/discussions/503

**Comment by fsaris** [comment]
New approach with temporary workaround for missing HA core functionality see #55

**Pull request closed without merging**
